version: '3'

services:
  webapplication1:
    image: webapplication1
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile

  webapplication2:
    image: webapplication2
    build:
      context: .
      dockerfile: WebApplication2/Dockerfile


  products.api:
    image: products.api
    build:
      context: .
      dockerfile: Source/Products.API/Dockerfile

